spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.79.135:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
  jpa:
    show-sql: true
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null  #全局配置，值为null的字段都不反回


server:
  servlet:
    context-path: /sell


#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    name: C:\test\sell.log
#  level:
#   root: debug