spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.79.135:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
  jpa:
    show-sql: true
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null  #全局配置，值为null的字段都不反回
  http:
    encoding:
      charset: utf-8
  freemarker:
    template-loader-path: classpath:/templates # classpath:  一定不能漏写
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: req
    suffix: .ftl



server:
  servlet:
    context-path: /sell


wechat:
  mpAppId: wxf2343asd2345lkj52345
  mpAppSecret: 234dan49d902nd0q3jhfas0f2

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    name: C:\test\sell.log
#  level:
#   root: debug